name: "AI Code Review Action v2"
description: "Advanced AI-powered code reviews with multiple model support"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  AI_PROVIDER:
    description: "AI provider (openai, anthropic, google)"
    required: true
    default: "openai"
  AI_MODEL:
    description: "AI model to use"
    required: true
    default: "gpt-4"
  AI_API_KEY:
    description: "API key for the chosen AI provider"
    required: true
  AI_TEMPERATURE:
    description: "Temperature for AI model (higher values = more creativity and variance)"
    required: false
    default: "0"
  APPROVE_REVIEWS:
    description: "Whether to approve/reject PRs automatically"
    required: false
    default: "true"
  MAX_COMMENTS:
    description: "Maximum number of review comments"
    required: false
    default: "0"
  PROJECT_CONTEXT:
    description: "Additional context about the project"
    required: false
  CONTEXT_FILES:
    description: "Files to include in review (comma-separated)"
    required: false
    default: "package.json,README.md"
  EXCLUDE_PATTERNS:
    description: "Files to exclude (glob patterns)"
    required: false
    default: "**/*.lock,**/*.json,**/*.md"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "code"
  color: "purple"
